### ISSUE TITLE
Forms don't submit on Safari 9.1

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/resource-center#64]
I think this has something to do with the use of Async/Await.

The components in question are views/story.js and views/ServiceRequest.js

**Comment by helderburato** [comment]
I would take this task.

**Comment by JesseRWeigel** [comment]
The form in story.js now works in Safari 9.1, but ServiceRequest.js is giving the follow error

```TypeError: n.uploadInput.files[Symbol.iterator] is not a function. (In 'n.uploadInput.files[Symbol.iterator]()', 'n.uploadInput.files[Symbol.iterator]' is undefined)```

There must be something being used to handle file uploads that is not supported by Safari 9.1, but I have not been able to find it yet.

**Comment by JesseRWeigel** [comment]
This error occurs on IE 11 as well. Getting "Symbol undefined" error.

**Comment by pantharshit00** [comment]
I got same error might include babel polyfill script tag or polyfill Io for older compatibility

**Comment by JesseRWeigel** [comment]
For now I have added a note for users that the form will not work on older browsers. It would still be nice to get this working at some point, but I can't spend any more time on it right now.
